import { defineSlotRecipe } from "@chakra-ui/react"

export const fileUploadSlotRecipe = defineSlotRecipe({
	base: {
		dropzone: {
			_dragging: {
				bg: "colorPalette.subtle",
				borderColor: "colorPalette.solid",
				borderStyle: "solid",
			},
			_hover: {
				bg: "bg.subtle",
			},
			alignItems: "center",
			background: "bg",
			borderRadius: "l3",
			borderStyle: "dashed",
			borderWidth: "2px",
			display: "flex",
			flexDirection: "column",
			focusVisibleRing: "outside",
			gap: "4",
			justifyContent: "center",
			minHeight: "2xs",
			px: "3",
			py: "2",
			transition: "backgrounds",
		},
		dropzoneContent: {
			alignItems: "center",
			display: "flex",
			flexDirection: "column",
			gap: "1",
			textAlign: "center",
			textStyle: "sm",
		},
		item: {
			alignItems: "center",
			animationDuration: "moderate",
			animationName: "fade-in",
			background: "bg",
			borderRadius: "l2",
			borderWidth: "1px",
			display: "flex",
			gap: "3",
			p: "4",
			pos: "relative",
			textStyle: "sm",
			width: "100%",
		},
		itemContent: {
			display: "flex",
			flex: "1",
			flexDirection: "column",
			gap: "0.5",
		},
		itemDeleteTrigger: {
			alignItems: "center",
			alignSelf: "flex-start",
			boxSize: "5",
			color: "fg.muted",
			cursor: "button",
			display: "flex",
			justifyContent: "center",
			p: "2px",
		},
		itemGroup: {
			_empty: {
				display: "none",
			},
			display: "flex",
			flexDirection: "column",
			gap: "3",
			width: "100%",
		},
		itemName: {
			color: "fg",
			fontWeight: "medium",
			lineClamp: "1",
		},
		itemPreview: {
			_icon: {
				boxSize: "4.5",
			},
			color: "fg.muted",
		},
		itemSizeText: {
			color: "fg.muted",
			textStyle: "xs",
		},
		label: {
			fontWeight: "medium",
			textStyle: "sm",
		},
		root: {
			alignItems: "flex-start",
			display: "flex",
			flexDirection: "column",
			gap: "4",
			width: "100%",
		},
	},
	className: "chakra-file-upload",
	defaultVariants: {},
	slots: [
		"root",
		"dropzone",
		"item",
		"itemDeleteTrigger",
		"itemGroup",
		"itemName",
		"itemPreview",
		"itemPreviewImage",
		"itemSizeText",
		"label",
		"trigger",
		"clearTrigger",
		"itemContent",
		"dropzoneContent",
		"fileText",
	],
})
