import { defineSlotRecipe } from "@chakra-ui/react";

export const toastSlotRecipe = defineSlotRecipe({
	base: {
		actionTrigger: {
			_hover: {
				bg: "var(--toast-trigger-bg)",
			},
			alignSelf: "center",
			borderColor: "var(--toast-border-color, inherit)",
			borderRadius: "l2",
			borderWidth: "1px",
			fontWeight: "medium",
			height: "8",
			px: "3",
			textStyle: "sm",
			transition: "background 200ms",
		},
		closeTrigger: {
			_icon: {
				boxSize: "1em",
			},
			alignItems: "center",
			borderRadius: "l2",
			color: "{currentColor/60}",
			display: "inline-flex",
			insetEnd: "1",
			justifyContent: "center",
			padding: "1",
			position: "absolute",
			textStyle: "md",
			top: "1",
			transition: "background 200ms",
		},
		description: {
			display: "inline",
			opacity: "0.8",
			textStyle: "sm",
		},
		indicator: {
			boxSize: "5",
			flexShrink: "0",
		},
		root: {
			_closed: {
				transition: "translate 400ms, scale 400ms, opacity 200ms",
				transitionTimingFunction: "cubic-bezier(0.06, 0.71, 0.55, 1)",
			},
			"--toast-trigger-bg": "colors.bg.muted",
			"&[data-type=error]": {
				"--toast-border-color": "{white/40}",
				"--toast-trigger-bg": "{white/10}",
				bg: "red.solid",
				color: "red.contrast",
			},
			"&[data-type=success]": {
				"--toast-border-color": "{white/40}",
				"--toast-trigger-bg": "{white/10}",
				bg: "green.solid",
				color: "green.contrast",
			},
			"&[data-type=warning]": {
				"--toast-border-color": "{white/40}",
				"--toast-trigger-bg": "{white/10}",
				bg: "orange.solid",
				color: "orange.contrast",
			},
			alignItems: "flex-start",
			bg: "bg.panel",
			borderRadius: "l2",
			boxShadow: "xl",
			color: "fg",
			display: "flex",
			gap: "3",
			height: "var(--height)",
			opacity: "var(--opacity)",
			pe: "6",
			position: "relative",
			ps: "4",
			py: "4",
			scale: "var(--scale)",
			transition:
				"translate 400ms, scale 400ms, opacity 400ms, height 400ms, box-shadow 200ms",
			transitionTimingFunction: "cubic-bezier(0.21, 1.02, 0.73, 1)",
			translate: "var(--x) var(--y)",
			width: "full",
			willChange: "translate, opacity, scale",
			zIndex: "var(--z-index)",
		},
		title: {
			fontWeight: "medium",
			marginEnd: "2",
			textStyle: "sm",
		},
	},
	className: "chakra-toast",
	slots: [
		"root",
		"title",
		"description",
		"indicator",
		"closeTrigger",
		"actionTrigger",
	],
});
