export interface TimezoneItem {
  code: string;
  country: string;
  flag: string;
  timeZone: string;
}

export const TZ_ITEMS: TimezoneItem[] = [
  { code: "AF", country: "Afghanistan", flag: "🇦🇫", timeZone: "Asia/Kabul" },
  { code: "AL", country: "Albania", flag: "🇦🇱", timeZone: "Europe/Tirane" },
  { code: "DZ", country: "Algeria", flag: "🇩🇿", timeZone: "Africa/Algiers" },
  {
    code: "AS",
    country: "American Samoa",
    flag: "🇦🇸",
    timeZone: "Pacific/Pago_Pago",
  },
  { code: "AD", country: "Andorra", flag: "🇦🇩", timeZone: "Europe/Andorra" },
  { code: "AO", country: "Angola", flag: "🇦🇴", timeZone: "Africa/Luanda" },
  { code: "AI", country: "Anguilla", flag: "🇦🇮", timeZone: "America/Anguilla" },
  {
    code: "AQ",
    country: "Antarctica",
    flag: "🇦🇶",
    timeZone: "Antarctica/McMurdo",
  },
  {
    code: "AG",
    country: "Antigua and Barbuda",
    flag: "🇦🇬",
    timeZone: "America/Antigua",
  },
  {
    code: "AR",
    country: "Argentina",
    flag: "🇦🇷",
    timeZone: "America/Argentina/Buenos_Aires",
  },
  { code: "AM", country: "Armenia", flag: "🇦🇲", timeZone: "Asia/Yerevan" },
  { code: "AW", country: "Aruba", flag: "🇦🇼", timeZone: "America/Aruba" },
  {
    code: "AU",
    country: "Australia",
    flag: "🇦🇺",
    timeZone: "Australia/Lord_Howe",
  },
  { code: "AT", country: "Austria", flag: "🇦🇹", timeZone: "Europe/Vienna" },
  { code: "AZ", country: "Azerbaijan", flag: "🇦🇿", timeZone: "Asia/Baku" },
  { code: "BS", country: "Bahamas", flag: "🇧🇸", timeZone: "America/Nassau" },
  { code: "BH", country: "Bahrain", flag: "🇧🇭", timeZone: "Asia/Bahrain" },
  { code: "BD", country: "Bangladesh", flag: "🇧🇩", timeZone: "Asia/Dhaka" },
  { code: "BB", country: "Barbados", flag: "🇧🇧", timeZone: "America/Barbados" },
  { code: "BY", country: "Belarus", flag: "🇧🇾", timeZone: "Europe/Minsk" },
  { code: "BE", country: "Belgium", flag: "🇧🇪", timeZone: "Europe/Brussels" },
  { code: "BZ", country: "Belize", flag: "🇧🇿", timeZone: "America/Belize" },
  { code: "BJ", country: "Benin", flag: "🇧🇯", timeZone: "Africa/Porto-Novo" },
  { code: "BM", country: "Bermuda", flag: "🇧🇲", timeZone: "Atlantic/Bermuda" },
  { code: "BT", country: "Bhutan", flag: "🇧🇹", timeZone: "Asia/Thimphu" },
  {
    code: "BO",
    country: "Bolivia, Plurinational State of",
    flag: "🇧🇴",
    timeZone: "America/La_Paz",
  },
  {
    code: "BQ",
    country: "Bonaire, Sint Eustatius and Saba",
    flag: "🇧🇶",
    timeZone: "America/Kralendijk",
  },
  {
    code: "BA",
    country: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    timeZone: "Europe/Sarajevo",
  },
  { code: "BW", country: "Botswana", flag: "🇧🇼", timeZone: "Africa/Gaborone" },
  { code: "BV", country: "Bouvet Island", flag: "🇧🇻", timeZone: "" },
  { code: "BR", country: "Brazil", flag: "🇧🇷", timeZone: "America/Noronha" },
  {
    code: "IO",
    country: "British Indian Ocean Territory",
    flag: "🇮🇴",
    timeZone: "Indian/Chagos",
  },
  {
    code: "BN",
    country: "Brunei Darussalam",
    flag: "🇧🇳",
    timeZone: "Asia/Brunei",
  },
  { code: "BG", country: "Bulgaria", flag: "🇧🇬", timeZone: "Europe/Sofia" },
  {
    code: "BF",
    country: "Burkina Faso",
    flag: "🇧🇫",
    timeZone: "Africa/Ouagadougou",
  },
  { code: "BI", country: "Burundi", flag: "🇧🇮", timeZone: "Africa/Bujumbura" },
  {
    code: "CV",
    country: "Cabo Verde",
    flag: "🇨🇻",
    timeZone: "Atlantic/Cape_Verde",
  },
  { code: "KH", country: "Cambodia", flag: "🇰🇭", timeZone: "Asia/Phnom_Penh" },
  { code: "CM", country: "Cameroon", flag: "🇨🇲", timeZone: "Africa/Douala" },
  { code: "CA", country: "Canada", flag: "🇨🇦", timeZone: "America/St_Johns" },
  {
    code: "KY",
    country: "Cayman Islands",
    flag: "🇰🇾",
    timeZone: "America/Cayman",
  },
  {
    code: "CF",
    country: "Central African Republic",
    flag: "🇨🇫",
    timeZone: "Africa/Bangui",
  },
  { code: "TD", country: "Chad", flag: "🇹🇩", timeZone: "Africa/Ndjamena" },
  { code: "CL", country: "Chile", flag: "🇨🇱", timeZone: "America/Santiago" },
  { code: "CN", country: "China", flag: "🇨🇳", timeZone: "Asia/Shanghai" },
  {
    code: "CX",
    country: "Christmas Island",
    flag: "🇨🇽",
    timeZone: "Indian/Christmas",
  },
  {
    code: "CC",
    country: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
    timeZone: "Indian/Cocos",
  },
  { code: "CO", country: "Colombia", flag: "🇨🇴", timeZone: "America/Bogota" },
  { code: "KM", country: "Comoros", flag: "🇰🇲", timeZone: "Indian/Comoro" },
  { code: "CG", country: "Congo", flag: "🇨🇬", timeZone: "Africa/Brazzaville" },
  {
    code: "CD",
    country: "Congo, The Democratic Republic of the",
    flag: "🇨🇩",
    timeZone: "Africa/Kinshasa",
  },
  {
    code: "CK",
    country: "Cook Islands",
    flag: "🇨🇰",
    timeZone: "Pacific/Rarotonga",
  },
  {
    code: "CR",
    country: "Costa Rica",
    flag: "🇨🇷",
    timeZone: "America/Costa_Rica",
  },
  { code: "HR", country: "Croatia", flag: "🇭🇷", timeZone: "Europe/Zagreb" },
  { code: "CU", country: "Cuba", flag: "🇨🇺", timeZone: "America/Havana" },
  { code: "CW", country: "Curaçao", flag: "🇨🇼", timeZone: "America/Curacao" },
  { code: "CY", country: "Cyprus", flag: "🇨🇾", timeZone: "Asia/Nicosia" },
  { code: "CZ", country: "Czechia", flag: "🇨🇿", timeZone: "Europe/Prague" },
  {
    code: "CI",
    country: "Côte d'Ivoire",
    flag: "🇨🇮",
    timeZone: "Africa/Abidjan",
  },
  { code: "DK", country: "Denmark", flag: "🇩🇰", timeZone: "Europe/Copenhagen" },
  { code: "DJ", country: "Djibouti", flag: "🇩🇯", timeZone: "Africa/Djibouti" },
  { code: "DM", country: "Dominica", flag: "🇩🇲", timeZone: "America/Dominica" },
  {
    code: "DO",
    country: "Dominican Republic",
    flag: "🇩🇴",
    timeZone: "America/Santo_Domingo",
  },
  { code: "EC", country: "Ecuador", flag: "🇪🇨", timeZone: "America/Guayaquil" },
  { code: "EG", country: "Egypt", flag: "🇪🇬", timeZone: "Africa/Cairo" },
  {
    code: "SV",
    country: "El Salvador",
    flag: "🇸🇻",
    timeZone: "America/El_Salvador",
  },
  {
    code: "GQ",
    country: "Equatorial Guinea",
    flag: "🇬🇶",
    timeZone: "Africa/Malabo",
  },
  { code: "ER", country: "Eritrea", flag: "🇪🇷", timeZone: "Africa/Asmara" },
  { code: "EE", country: "Estonia", flag: "🇪🇪", timeZone: "Europe/Tallinn" },
  { code: "SZ", country: "Eswatini", flag: "🇸🇿", timeZone: "Africa/Mbabane" },
  {
    code: "ET",
    country: "Ethiopia",
    flag: "🇪🇹",
    timeZone: "Africa/Addis_Ababa",
  },
  {
    code: "FK",
    country: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    timeZone: "Atlantic/Stanley",
  },
  {
    code: "FO",
    country: "Faroe Islands",
    flag: "🇫🇴",
    timeZone: "Atlantic/Faroe",
  },
  { code: "FJ", country: "Fiji", flag: "🇫🇯", timeZone: "Pacific/Fiji" },
  { code: "FI", country: "Finland", flag: "🇫🇮", timeZone: "Europe/Helsinki" },
  { code: "FR", country: "France", flag: "🇫🇷", timeZone: "Europe/Paris" },
  {
    code: "GF",
    country: "French Guiana",
    flag: "🇬🇫",
    timeZone: "America/Cayenne",
  },
  {
    code: "PF",
    country: "French Polynesia",
    flag: "🇵🇫",
    timeZone: "Pacific/Tahiti",
  },
  {
    code: "TF",
    country: "French Southern Territories",
    flag: "🇹🇫",
    timeZone: "Indian/Kerguelen",
  },
  { code: "GA", country: "Gabon", flag: "🇬🇦", timeZone: "Africa/Libreville" },
  { code: "GM", country: "Gambia", flag: "🇬🇲", timeZone: "Africa/Banjul" },
  { code: "GE", country: "Georgia", flag: "🇬🇪", timeZone: "Asia/Tbilisi" },
  { code: "DE", country: "Germany", flag: "🇩🇪", timeZone: "Europe/Berlin" },
  { code: "GH", country: "Ghana", flag: "🇬🇭", timeZone: "Africa/Accra" },
  {
    code: "GI",
    country: "Gibraltar",
    flag: "🇬🇮",
    timeZone: "Europe/Gibraltar",
  },
  { code: "GR", country: "Greece", flag: "🇬🇷", timeZone: "Europe/Athens" },
  { code: "GL", country: "Greenland", flag: "🇬🇱", timeZone: "America/Nuuk" },
  { code: "GD", country: "Grenada", flag: "🇬🇩", timeZone: "America/Grenada" },
  {
    code: "GP",
    country: "Guadeloupe",
    flag: "🇬🇵",
    timeZone: "America/Guadeloupe",
  },
  { code: "GU", country: "Guam", flag: "🇬🇺", timeZone: "Pacific/Guam" },
  {
    code: "GT",
    country: "Guatemala",
    flag: "🇬🇹",
    timeZone: "America/Guatemala",
  },
  { code: "GG", country: "Guernsey", flag: "🇬🇬", timeZone: "Europe/Guernsey" },
  { code: "GN", country: "Guinea", flag: "🇬🇳", timeZone: "Africa/Conakry" },
  {
    code: "GW",
    country: "Guinea-Bissau",
    flag: "🇬🇼",
    timeZone: "Africa/Bissau",
  },
  { code: "GY", country: "Guyana", flag: "🇬🇾", timeZone: "America/Guyana" },
  {
    code: "HT",
    country: "Haiti",
    flag: "🇭🇹",
    timeZone: "America/Port-au-Prince",
  },
  {
    code: "HM",
    country: "Heard Island and McDonald Islands",
    flag: "🇭🇲",
    timeZone: "",
  },
  {
    code: "VA",
    country: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    timeZone: "Europe/Vatican",
  },
  {
    code: "HN",
    country: "Honduras",
    flag: "🇭🇳",
    timeZone: "America/Tegucigalpa",
  },
  { code: "HK", country: "Hong Kong", flag: "🇭🇰", timeZone: "Asia/Hong_Kong" },
  { code: "HU", country: "Hungary", flag: "🇭🇺", timeZone: "Europe/Budapest" },
  {
    code: "IS",
    country: "Iceland",
    flag: "🇮🇸",
    timeZone: "Atlantic/Reykjavik",
  },
  { code: "IN", country: "India", flag: "🇮🇳", timeZone: "Asia/Kolkata" },
  { code: "ID", country: "Indonesia", flag: "🇮🇩", timeZone: "Asia/Jakarta" },
  {
    code: "IR",
    country: "Iran",
    flag: "🇮🇷",
    timeZone: "Asia/Tehran",
  },
  { code: "IQ", country: "Iraq", flag: "🇮🇶", timeZone: "Asia/Baghdad" },
  { code: "IE", country: "Ireland", flag: "🇮🇪", timeZone: "Europe/Dublin" },
  {
    code: "IM",
    country: "Isle of Man",
    flag: "🇮🇲",
    timeZone: "Europe/Isle_of_Man",
  },
  { code: "IL", country: "Israel", flag: "🇮🇱", timeZone: "Asia/Jerusalem" },
  { code: "IT", country: "Italy", flag: "🇮🇹", timeZone: "Europe/Rome" },
  { code: "JM", country: "Jamaica", flag: "🇯🇲", timeZone: "America/Jamaica" },
  { code: "JP", country: "Japan", flag: "🇯🇵", timeZone: "Asia/Tokyo" },
  { code: "JE", country: "Jersey", flag: "🇯🇪", timeZone: "Europe/Jersey" },
  { code: "JO", country: "Jordan", flag: "🇯🇴", timeZone: "Asia/Amman" },
  { code: "KZ", country: "Kazakhstan", flag: "🇰🇿", timeZone: "Asia/Almaty" },
  { code: "KE", country: "Kenya", flag: "🇰🇪", timeZone: "Africa/Nairobi" },
  { code: "KI", country: "Kiribati", flag: "🇰🇮", timeZone: "Pacific/Tarawa" },
  {
    code: "KP",
    country: "Korea, Democratic People's Republic of",
    flag: "🇰🇵",
    timeZone: "Asia/Pyongyang",
  },
  {
    code: "KR",
    country: "Korea, Republic of",
    flag: "🇰🇷",
    timeZone: "Asia/Seoul",
  },
  { code: "KW", country: "Kuwait", flag: "🇰🇼", timeZone: "Asia/Kuwait" },
  { code: "KG", country: "Kyrgyzstan", flag: "🇰🇬", timeZone: "Asia/Bishkek" },
  {
    code: "LA",
    country: "Lao People's Democratic Republic",
    flag: "🇱🇦",
    timeZone: "Asia/Vientiane",
  },
  { code: "LV", country: "Latvia", flag: "🇱🇻", timeZone: "Europe/Riga" },
  { code: "LB", country: "Lebanon", flag: "🇱🇧", timeZone: "Asia/Beirut" },
  { code: "LS", country: "Lesotho", flag: "🇱🇸", timeZone: "Africa/Maseru" },
  { code: "LR", country: "Liberia", flag: "🇱🇷", timeZone: "Africa/Monrovia" },
  { code: "LY", country: "Libya", flag: "🇱🇾", timeZone: "Africa/Tripoli" },
  {
    code: "LI",
    country: "Liechtenstein",
    flag: "🇱🇮",
    timeZone: "Europe/Vaduz",
  },
  { code: "LT", country: "Lithuania", flag: "🇱🇹", timeZone: "Europe/Vilnius" },
  {
    code: "LU",
    country: "Luxembourg",
    flag: "🇱🇺",
    timeZone: "Europe/Luxembourg",
  },
  { code: "MO", country: "Macao", flag: "🇲🇴", timeZone: "Asia/Macau" },
  {
    code: "MG",
    country: "Madagascar",
    flag: "🇲🇬",
    timeZone: "Indian/Antananarivo",
  },
  { code: "MW", country: "Malawi", flag: "🇲🇼", timeZone: "Africa/Blantyre" },
  {
    code: "MY",
    country: "Malaysia",
    flag: "🇲🇾",
    timeZone: "Asia/Kuala_Lumpur",
  },
  { code: "MV", country: "Maldives", flag: "🇲🇻", timeZone: "Indian/Maldives" },
  { code: "ML", country: "Mali", flag: "🇲🇱", timeZone: "Africa/Bamako" },
  { code: "MT", country: "Malta", flag: "🇲🇹", timeZone: "Europe/Malta" },
  {
    code: "MH",
    country: "Marshall Islands",
    flag: "🇲🇭",
    timeZone: "Pacific/Majuro",
  },
  {
    code: "MQ",
    country: "Martinique",
    flag: "🇲🇶",
    timeZone: "America/Martinique",
  },
  {
    code: "MR",
    country: "Mauritania",
    flag: "🇲🇷",
    timeZone: "Africa/Nouakchott",
  },
  {
    code: "MU",
    country: "Mauritius",
    flag: "🇲🇺",
    timeZone: "Indian/Mauritius",
  },
  { code: "YT", country: "Mayotte", flag: "🇾🇹", timeZone: "Indian/Mayotte" },
  {
    code: "MX",
    country: "Mexico",
    flag: "🇲🇽",
    timeZone: "America/Mexico_City",
  },
  {
    code: "FM",
    country: "Micronesia, Federated States of",
    flag: "🇫🇲",
    timeZone: "Pacific/Chuuk",
  },
  {
    code: "MD",
    country: "Moldova, Republic of",
    flag: "🇲🇩",
    timeZone: "Europe/Chisinau",
  },
  { code: "MC", country: "Monaco", flag: "🇲🇨", timeZone: "Europe/Monaco" },
  { code: "MN", country: "Mongolia", flag: "🇲🇳", timeZone: "Asia/Ulaanbaatar" },
  {
    code: "ME",
    country: "Montenegro",
    flag: "🇲🇪",
    timeZone: "Europe/Podgorica",
  },
  {
    code: "MS",
    country: "Montserrat",
    flag: "🇲🇸",
    timeZone: "America/Montserrat",
  },
  { code: "MA", country: "Morocco", flag: "🇲🇦", timeZone: "Africa/Casablanca" },
  { code: "MZ", country: "Mozambique", flag: "🇲🇿", timeZone: "Africa/Maputo" },
  { code: "MM", country: "Myanmar", flag: "🇲🇲", timeZone: "Asia/Yangon" },
  { code: "NA", country: "Namibia", flag: "🇳🇦", timeZone: "Africa/Windhoek" },
  { code: "NR", country: "Nauru", flag: "🇳🇷", timeZone: "Pacific/Nauru" },
  { code: "NP", country: "Nepal", flag: "🇳🇵", timeZone: "Asia/Kathmandu" },
  {
    code: "NL",
    country: "Netherlands",
    flag: "🇳🇱",
    timeZone: "Europe/Amsterdam",
  },
  {
    code: "NC",
    country: "New Caledonia",
    flag: "🇳🇨",
    timeZone: "Pacific/Noumea",
  },
  {
    code: "NZ",
    country: "New Zealand",
    flag: "🇳🇿",
    timeZone: "Pacific/Auckland",
  },
  { code: "NI", country: "Nicaragua", flag: "🇳🇮", timeZone: "America/Managua" },
  { code: "NE", country: "Niger", flag: "🇳🇪", timeZone: "Africa/Niamey" },
  { code: "NG", country: "Nigeria", flag: "🇳🇬", timeZone: "Africa/Lagos" },
  { code: "NU", country: "Niue", flag: "🇳🇺", timeZone: "Pacific/Niue" },
  {
    code: "NF",
    country: "Norfolk Island",
    flag: "🇳🇫",
    timeZone: "Pacific/Norfolk",
  },
  {
    code: "MK",
    country: "North Macedonia",
    flag: "🇲🇰",
    timeZone: "Europe/Skopje",
  },
  {
    code: "MP",
    country: "Northern Mariana Islands",
    flag: "🇲🇵",
    timeZone: "Pacific/Saipan",
  },
  { code: "NO", country: "Norway", flag: "🇳🇴", timeZone: "Europe/Oslo" },
  { code: "OM", country: "Oman", flag: "🇴🇲", timeZone: "Asia/Muscat" },
  { code: "PK", country: "Pakistan", flag: "🇵🇰", timeZone: "Asia/Karachi" },
  { code: "PW", country: "Palau", flag: "🇵🇼", timeZone: "Pacific/Palau" },
  {
    code: "PS",
    country: "Palestine, State of",
    flag: "🇵🇸",
    timeZone: "Asia/Gaza",
  },
  { code: "PA", country: "Panama", flag: "🇵🇦", timeZone: "America/Panama" },
  {
    code: "PG",
    country: "Papua New Guinea",
    flag: "🇵🇬",
    timeZone: "Pacific/Port_Moresby",
  },
  { code: "PY", country: "Paraguay", flag: "🇵🇾", timeZone: "America/Asuncion" },
  { code: "PE", country: "Peru", flag: "🇵🇪", timeZone: "America/Lima" },
  { code: "PH", country: "Philippines", flag: "🇵🇭", timeZone: "Asia/Manila" },
  { code: "PN", country: "Pitcairn", flag: "🇵🇳", timeZone: "Pacific/Pitcairn" },
  { code: "PL", country: "Poland", flag: "🇵🇱", timeZone: "Europe/Warsaw" },
  { code: "PT", country: "Portugal", flag: "🇵🇹", timeZone: "Europe/Lisbon" },
  {
    code: "PR",
    country: "Puerto Rico",
    flag: "🇵🇷",
    timeZone: "America/Puerto_Rico",
  },
  { code: "QA", country: "Qatar", flag: "🇶🇦", timeZone: "Asia/Qatar" },
  { code: "RO", country: "Romania", flag: "🇷🇴", timeZone: "Europe/Bucharest" },
  {
    code: "RU",
    country: "Russian Federation",
    flag: "🇷🇺",
    timeZone: "Europe/Kaliningrad",
  },
  { code: "RW", country: "Rwanda", flag: "🇷🇼", timeZone: "Africa/Kigali" },
  { code: "RE", country: "Réunion", flag: "🇷🇪", timeZone: "Indian/Reunion" },
  {
    code: "BL",
    country: "Saint Barthélemy",
    flag: "🇧🇱",
    timeZone: "America/St_Barthelemy",
  },
  {
    code: "SH",
    country: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "🇸🇭",
    timeZone: "Atlantic/St_Helena",
  },
  {
    code: "KN",
    country: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    timeZone: "America/St_Kitts",
  },
  {
    code: "LC",
    country: "Saint Lucia",
    flag: "🇱🇨",
    timeZone: "America/St_Lucia",
  },
  {
    code: "MF",
    country: "Saint Martin (French part)",
    flag: "🇲🇫",
    timeZone: "America/Marigot",
  },
  {
    code: "PM",
    country: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    timeZone: "America/Miquelon",
  },
  {
    code: "VC",
    country: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    timeZone: "America/St_Vincent",
  },
  { code: "WS", country: "Samoa", flag: "🇼🇸", timeZone: "Pacific/Apia" },
  {
    code: "SM",
    country: "San Marino",
    flag: "🇸🇲",
    timeZone: "Europe/San_Marino",
  },
  {
    code: "ST",
    country: "Sao Tome and Principe",
    flag: "🇸🇹",
    timeZone: "Africa/Sao_Tome",
  },
  { code: "SA", country: "Saudi Arabia", flag: "🇸🇦", timeZone: "Asia/Riyadh" },
  { code: "SN", country: "Senegal", flag: "🇸🇳", timeZone: "Africa/Dakar" },
  { code: "RS", country: "Serbia", flag: "🇷🇸", timeZone: "Europe/Belgrade" },
  { code: "SC", country: "Seychelles", flag: "🇸🇨", timeZone: "Indian/Mahe" },
  {
    code: "SL",
    country: "Sierra Leone",
    flag: "🇸🇱",
    timeZone: "Africa/Freetown",
  },
  { code: "SG", country: "Singapore", flag: "🇸🇬", timeZone: "Asia/Singapore" },
  {
    code: "SX",
    country: "Sint Maarten (Dutch part)",
    flag: "🇸🇽",
    timeZone: "America/Lower_Princes",
  },
  {
    code: "SK",
    country: "Slovakia",
    flag: "🇸🇰",
    timeZone: "Europe/Bratislava",
  },
  { code: "SI", country: "Slovenia", flag: "🇸🇮", timeZone: "Europe/Ljubljana" },
  {
    code: "SB",
    country: "Solomon Islands",
    flag: "🇸🇧",
    timeZone: "Pacific/Guadalcanal",
  },
  { code: "SO", country: "Somalia", flag: "🇸🇴", timeZone: "Africa/Mogadishu" },
  {
    code: "ZA",
    country: "South Africa",
    flag: "🇿🇦",
    timeZone: "Africa/Johannesburg",
  },
  {
    code: "GS",
    country: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    timeZone: "Atlantic/South_Georgia",
  },
  { code: "SS", country: "South Sudan", flag: "🇸🇸", timeZone: "Africa/Juba" },
  { code: "ES", country: "Spain", flag: "🇪🇸", timeZone: "Europe/Madrid" },
  { code: "LK", country: "Sri Lanka", flag: "🇱🇰", timeZone: "Asia/Colombo" },
  { code: "SD", country: "Sudan", flag: "🇸🇩", timeZone: "Africa/Khartoum" },
  {
    code: "SR",
    country: "Suriname",
    flag: "🇸🇷",
    timeZone: "America/Paramaribo",
  },
  {
    code: "SJ",
    country: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    timeZone: "Arctic/Longyearbyen",
  },
  { code: "SE", country: "Sweden", flag: "🇸🇪", timeZone: "Europe/Stockholm" },
  { code: "CH", country: "Switzerland", flag: "🇨🇭", timeZone: "Europe/Zurich" },
  {
    code: "SY",
    country: "Syrian Arab Republic",
    flag: "🇸🇾",
    timeZone: "Asia/Damascus",
  },
  {
    code: "TW",
    country: "Taiwan, Province of China",
    flag: "🇹🇼",
    timeZone: "Asia/Taipei",
  },
  { code: "TJ", country: "Tajikistan", flag: "🇹🇯", timeZone: "Asia/Dushanbe" },
  {
    code: "TZ",
    country: "Tanzania, United Republic of",
    flag: "🇹🇿",
    timeZone: "Africa/Dar_es_Salaam",
  },
  { code: "TH", country: "Thailand", flag: "🇹🇭", timeZone: "Asia/Bangkok" },
  { code: "TL", country: "Timor-Leste", flag: "🇹🇱", timeZone: "Asia/Dili" },
  { code: "TG", country: "Togo", flag: "🇹🇬", timeZone: "Africa/Lome" },
  { code: "TK", country: "Tokelau", flag: "🇹🇰", timeZone: "Pacific/Fakaofo" },
  { code: "TO", country: "Tonga", flag: "🇹🇴", timeZone: "Pacific/Tongatapu" },
  {
    code: "TT",
    country: "Trinidad and Tobago",
    flag: "🇹🇹",
    timeZone: "America/Port_of_Spain",
  },
  { code: "TN", country: "Tunisia", flag: "🇹🇳", timeZone: "Africa/Tunis" },
  { code: "TR", country: "Turkey", flag: "🇹🇷", timeZone: "Europe/Istanbul" },
  {
    code: "TM",
    country: "Turkmenistan",
    flag: "🇹🇲",
    timeZone: "Asia/Ashgabat",
  },
  {
    code: "TC",
    country: "Turks and Caicos Islands",
    flag: "🇹🇨",
    timeZone: "America/Grand_Turk",
  },
  { code: "TV", country: "Tuvalu", flag: "🇹🇻", timeZone: "Pacific/Funafuti" },
  { code: "UG", country: "Uganda", flag: "🇺🇬", timeZone: "Africa/Kampala" },
  { code: "UA", country: "Ukraine", flag: "🇺🇦", timeZone: "Europe/Simferopol" },
  {
    code: "AE",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    timeZone: "Asia/Dubai",
  },
  {
    code: "GB",
    country: "United Kingdom",
    flag: "🇬🇧",
    timeZone: "Europe/London",
  },
  {
    code: "US",
    country: "United States",
    flag: "🇺🇸",
    timeZone: "America/New_York",
  },
  {
    code: "UM",
    country: "United States Minor Outlying Islands",
    flag: "🇺🇲",
    timeZone: "Pacific/Midway",
  },
  {
    code: "UY",
    country: "Uruguay",
    flag: "🇺🇾",
    timeZone: "America/Montevideo",
  },
  { code: "UZ", country: "Uzbekistan", flag: "🇺🇿", timeZone: "Asia/Samarkand" },
  { code: "VU", country: "Vanuatu", flag: "🇻🇺", timeZone: "Pacific/Efate" },
  {
    code: "VE",
    country: "Venezuela, Bolivarian Republic of",
    flag: "🇻🇪",
    timeZone: "America/Caracas",
  },
  { code: "VN", country: "Viet Nam", flag: "🇻🇳", timeZone: "Asia/Ho_Chi_Minh" },
  {
    code: "VG",
    country: "Virgin Islands, British",
    flag: "🇻🇬",
    timeZone: "America/Tortola",
  },
  {
    code: "VI",
    country: "Virgin Islands, U.S.",
    flag: "🇻🇮",
    timeZone: "America/St_Thomas",
  },
  {
    code: "WF",
    country: "Wallis and Futuna",
    flag: "🇼🇫",
    timeZone: "Pacific/Wallis",
  },
  {
    code: "EH",
    country: "Western Sahara",
    flag: "🇪🇭",
    timeZone: "Africa/El_Aaiun",
  },
  { code: "YE", country: "Yemen", flag: "🇾🇪", timeZone: "Asia/Aden" },
  { code: "ZM", country: "Zambia", flag: "🇿🇲", timeZone: "Africa/Lusaka" },
  { code: "ZW", country: "Zimbabwe", flag: "🇿🇼", timeZone: "Africa/Harare" },
  {
    code: "AX",
    country: "Åland Islands",
    flag: "🇦🇽",
    timeZone: "Europe/Mariehamn",
  },
];
